In [24]:
from cil.framework import ImageGeometry, ImageData
from cil.optimisation.operators import DiagonalOperator, ChannelwiseOperator
import numpy as np


M = 3
channels = 2
ig = ImageGeometry(M, M, channels=channels)
single_ig = ImageGeometry(M, M)
x = ImageData( np.stack( [np.ones((M,M)),  2*np.ones((M,M))] , axis=0), geometry=ig )
diag = ImageData(np.array(range(M*M), dtype=np.float64).reshape((M,M)), geometry=single_ig)
D = DiagonalOperator(diag)
C = ChannelwiseOperator(D,channels)
y = C.direct(x)
print('The original image data is:')
print(x.as_array())
print('The channel wise operators multiplies each channel element wise by:')
print(diag.as_array())
print('The result of applying the channel wise operator is:')
print(y.as_array())

The original image data is:
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
The channel wise operators multiplies each channel element wise by:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
The result of applying the channel wise operator is:
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 0.  2.  4.]
  [ 6.  8. 10.]
  [12. 14. 16.]]]


In [18]:
np.array(range(M*M), dtype=np.float64).reshape((M,M))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])