In [2]:

 
import numpy as np
import matplotlib.pyplot as plt
import os
from cil.framework import Sampler


In [17]:
sampler=Sampler.sequential(10)
print(sampler.get_samples(20))
for _ in range(11):
    print(sampler.next())

next(sampler)
np.array([0 ,1 ,2 ,3, 4, 5, 6 ,7, 8, 9, 0 ,1,2 ,3 ,4, 5, 6 ,7, 8, 9])

SyntaxError: invalid syntax (322026347.py, line 7)

In [15]:
sampler=Sampler.randomWithoutReplacement(8, shuffle=False, seed=1)
print(list(sampler.get_samples(8)))



[7, 2, 1, 6, 0, 4, 3, 5]


In [10]:
sampler=Sampler.hermanMeyer(12)
print(sampler.get_samples(16))
for _ in range(15):
    print(next(sampler))

print(sampler.order)

[ 0  6  3  9  1  7  4 10  2  8  5 11  0  6  3  9]
0
6
3
9
1
7
4
10
2
8
5
11
0
6
3
[0, 6, 3, 9, 1, 7, 4, 10, 2, 8, 5, 11]


In [21]:
sampler=Sampler.randomWithReplacement(5, seed=5)
for _ in range(12):
    print(sampler.next())
print(list(sampler.get_samples(25)))


1
4
1
4
2
3
3
2
1
0
0
3
[1, 4, 1, 4, 2, 3, 3, 2, 1, 0, 0, 3, 2, 0, 4, 1, 2, 1, 3, 2, 2, 1, 1, 1, 1]


In [13]:
sampler=Sampler.randomWithReplacement(4, [0.7,0.1,0.1,0.1], seed=5)
print(list(sampler.get_samples(25)))

[0, 2, 0, 3, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [8]:
sampler=Sampler.staggered(21,4)
print(sampler.get_samples(5))
for _ in range(15):
    print(sampler.next())
print(sampler.get_samples(5))

print(sampler.order)

[ 0  4  8 12 16]
0
4
8
12
16
20
1
5
9
13
17
2
6
10
14
[ 0  4  8 12 16]
[0, 4, 8, 12, 16, 20, 1, 5, 9, 13, 17, 2, 6, 10, 14, 18, 3, 7, 11, 15, 19]


In [9]:
sampler=Sampler.customOrder([1,4,6,7,8,9,11])
print(sampler.get_samples(11))
for _ in range(9):
    print(sampler.next())
print(sampler.get_samples(5))

[ 1  4  6  7  8  9 11  1  4  6  7]
1
4
6
7
8
9
11
1
4
[1 4 6 7 8]
